version: "3.9"
services:

  db:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_DB: postgres_name
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=DEV-faze
      - DEBUG=False
      - CORS_ALLOWED_ORIGINS=http://127.0.0.1:8000  # use another hosts like -> host1, host2, ...
      - EMAIL_HOST_USER=dev@gamil.com
      - EMAIL_HOST_PASSWORD = dev123!!
      - CRYPTOGRAPHY_KEY=lSUr-ch8fT33W3y9braWZsTnm6bBKWPKcU7D2Khr7Sg=
    depends_on:
      - redis
      - db

  daphne:
    build: .
    container_name: websocket
    command: bash -c "daphne -b 0.0.0.0 -p 8001 core.asgi:application"
    depends_on:
      - backend
      - redis
      - db
    volumes:
      - ./core:/app
    expose:
      - "8001"
    environment:
      - SECRET_KEY=DEV-faze
      - DEBUG=False
      - CORS_ALLOWED_ORIGINS=http://127.0.0.1:8000  # use another hosts like -> host1, host2, ...
      - EMAIL_HOST_USER=dev@gamil.com
      - EMAIL_HOST_PASSWORD = dev123!!
      - CRYPTOGRAPHY_KEY=lSUr-ch8fT33W3y9braWZsTnm6bBKWPKcU7D2Khr7Sg=

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend
      - db
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=DEV-faze
      - DEBUG=False
      - CORS_ALLOWED_ORIGINS=http://127.0.0.1:8000  # use another hosts like -> host1, host2, ...
      - EMAIL_HOST_USER=dev@gamil.com
      - EMAIL_HOST_PASSWORD = dev123!!
      - CRYPTOGRAPHY_KEY=lSUr-ch8fT33W3y9braWZsTnm6bBKWPKcU7D2Khr7Sg=

  schedule_worker:
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - backend
      - worker
      - db
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=DEV-faze
      - DEBUG=False
      - CORS_ALLOWED_ORIGINS=http://127.0.0.1:8000  # use another hosts like -> host1, host2, ...
      - EMAIL_HOST_USER=dev@gamil.com
      - EMAIL_HOST_PASSWORD = dev123!!
      - CRYPTOGRAPHY_KEY=lSUr-ch8fT33W3y9braWZsTnm6bBKWPKcU7D2Khr7Sg=

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend
      - worker
      - schedule_worker
      - daphne
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
