version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=DEV-faze
      - DEBUG=True
      - CORS_ALLOWED_ORIGINS=http://127.0.0.1:8000  # use another hosts like -> host1, host2, ...
      - EMAIL_HOST_USER=dev@gamil.com
      - EMAIL_HOST_PASSWORD = dev123!!
    depends_on:
      - redis
  
  # worker:
  #   build: .
  #   command: celery -A core worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - backend
  #   volumes:
  #     - ./core:/app
  #   environment:
  #     - SECRET_KEY=test
  #     - DEBUG=False
  
  # schedule_worker:
  #   build: .
  #   command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   depends_on:
  #     - redis
  #     - backend
  #     - worker
  #   volumes:
  #     - ./core:/app
  #   environment:
  #     - SECRET_KEY=test
  #     - DEBUG=False

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data: