# Generated by Django 5.1 on 2024-08-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trackingusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingusermodel',
            name='session_key',
        ),
    ]
