# Generated by Django 5.1 on 2024-08-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_trackingusermodel_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingusermodel',
            name='updated',
        ),
    ]
