# Generated by Django 5.1 on 2024-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
