# Generated by Django 5.0 on 2024-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_alter_messagegroupmodel_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagemodel",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
