# Generated by Django 5.0 on 2024-09-02 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0004_alter_messagemodel_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagegroupmodel",
            name="online_users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
