# Generated by Django 5.1 on 2024-08-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcontentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog-files/%y/%m/%d/'),
        ),
    ]
