# Generated by Django 5.0 on 2024-08-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcontentmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
