# Generated by Django 5.0 on 2024-09-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogmodel_created_alter_blogmodel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
