# Generated by Django 5.0 on 2024-09-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_blogcontentmodel_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcontentmodel",
            options={"ordering": ["-created", "id"]},
        ),
        migrations.AlterModelOptions(
            name="blogmodel",
            options={"ordering": ["-updated", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"ordering": ("name", "id")},
        ),
    ]
